package com.taylorthurman.playground.adventofcode.christmas2022;

import java.util.HashMap;
import java.util.Map;

public class Day2RockPaperScissors {

    public static void main(String[] args) {
        part1();
        part2();
    }

    private static void part1() {
        Map<String, Integer> matchKey = new HashMap<>();
        matchKey.put("X", 1);
        matchKey.put("Y", 2);
        matchKey.put("Z", 3);
        matchKey.put("C X", 6);
        matchKey.put("A Y", 6);
        matchKey.put("B Z", 6);
        matchKey.put("A X", 3);
        matchKey.put("B Y", 3);
        matchKey.put("C Z", 6);

        String[] matches = input.split("\\R");
        int total = 0;
        for (int i = 0; i < matches.length; i++) {
            String yourMove = Character.toString(matches[i].charAt(2));
            total += matchKey.get(yourMove);
            if (matchKey.containsKey(matches[i])) {
                total += matchKey.get(matches[i]);
            }
        }

        System.out.println(total);
    }

    private static void part2() {
        Map<String, Integer> matchKey = new HashMap<>();
        matchKey.put("A", 1);
        matchKey.put("B", 2);
        matchKey.put("C", 3);
        matchKey.put("X", 0);
        matchKey.put("Y", 3);
        matchKey.put("Z", 6);

        Map<String, String> winKey = new HashMap<>();
        winKey.put("A", "B");
        winKey.put("B", "C");
        winKey.put("C", "A");

        Map<String, String> loseKey = new HashMap<>();
        loseKey.put("A", "C");
        loseKey.put("B", "A");
        loseKey.put("C", "B");

        String[] matches = input.split("\\R");
        int total = 0;
        for (String match : matches) {
            String matchOutcome = Character.toString(match.charAt(2));
            String oppMove = Character.toString(match.charAt(0));
            total += matchKey.get(matchOutcome);
            if (matchOutcome.equals("Z")) total += matchKey.get(winKey.get(oppMove));
            else if (matchOutcome.equals("Y")) total += matchKey.get(oppMove);
            else {
                total += matchKey.get(loseKey.get(oppMove));
            }
        }

        System.out.println(total);
    }

    private static final String input = "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z";
}

